name: group_alarm_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure your SDK version is compatible

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.11 # Ensure this is the latest version
  firebase_core: ^2.27.0 # Latest stable version
  firebase_auth: ^4.17.8 # Latest stable version
  js: ^0.6.7 # Add the js package dependency
  cloud_firestore: ^4.15.8 # Latest stable version
  # Add other dependencies as you need them
  # For example, if you use http for the AI chat:
  # http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # flutter_native_splash: ^2.3.11 # Same version as above
  firebase_crashlytics: ^3.4.17 # Good for error reporting
  firebase_analytics: ^10.8.9 # Good for analytics

flutter:
  uses-material-design: true
  # assets:
  #   - assets/ # If you have a logo.png in assets/
